### PR TITLE
Mips N32 support

### PR DESCRIPTION
**Pull request by KoviRobi**
This is applying https://reviews.llvm.org/D21465, https://reviews.llvm.org/D21467 and https://reviews.llvm.org/D21292 with my own changes to make them work.

* The first patch replaces -target-abi with -mabi.

* The second patch adds the ABI information to the triple, plus adds specifying the ABI in the triple too (to which I also have added a purecap option, e.g. cheri-unknown-freebsd-purecap).

* The third patch uses the correct relocation for N32 with the information provided.

This also requires the clang pull request https://github.com/CTSRD-CHERI/clang/pull/150 to be merged

### CODE REVIEW

**Comment by KoviRobi** [comment]
In patch 1, all the.ll and the .s changes, EXCEPT test/CodeGen/Mips/cheri-member-pointer-init.ll and test/MC/Mips/macro-li.d.s are just changing "-target-abi[ =]" to "-mabi=".

* test/CodeGen/Mips/cheri-member-pointer-init.ll replaces "-target-abi sandbox" to "-mabi=purecap"

* test/MC/Mips/macro-li.d.s renames the O32 FileCheck prefix to O32-32BIT-FPR (32-bit floating point register), as there is another `# RUN` line with an O32 ABI but with 64-bit floating point registers which did not have the O32 prefix. Now both have the O32 prefix, this just clarifies things here, but in the next patch it will be used to split the N32/N64 from the O32, as N32/N64 former uses `.Llabel`, while O32 uses `$label`.

**Comment by KoviRobi** [comment]
Actually, looking at it again, it seems like the `$label` to `.Llabel` might be a bug, as https://github.com/CTSRD-CHERI/llvm/blob/master/lib/Target/Mips/MCTargetDesc/MipsMCAsmInfo.cpp#33 has
```
  if ((TheTriple.getArch() == Triple::mipsel) ||
      (TheTriple.getArch() == Triple::mips)) {
    PrivateGlobalPrefix = "$";
    PrivateLabelPrefix = "$";
  }
```

and the triple is specified as `mipsel-unknown-linux`, so the prefix should be "$"

**Comment by RichardsonAlex** [comment]
I would prefer if we could leave this in a branch until the reviews have been committed upstream.

As the person who is currently doing the upstream merges I would like to avoid the tons of merge conflicts in case a slightly different version of the patch gets committed. It is already quite annoying with the MIPS multigot patch in LLD and that only touches a few files.

**Comment by davidchisnall** [comment]
I agree.  If these things are all under review upstream, we should put them into a branch.  @KoviRobi it would probably be a good idea for you to comment on the upstream reviews if you see any issues with the patches.

**Comment by KoviRobi** [comment]
Okay, thanks, I'll do that, though not sure when they will be merged upstream, they seem to not have a lot of interest, most of the comments on the reviews are just "rebase and ping".

**Pull request closed without merging**
